FROM ubuntu:20.04

RUN apt-get update && \
    apt-get upgrade --yes

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y \
    software-properties-common \
    python3 \
    python3-pip \
    curl \
    ca-certificates \
    git \
    bzip2 \
    libx11-6 \
    tmux \
    gcc \
    g++ \
    python3-dev \
 && rm -rf /var/lib/apt/lists/*

RUN pip3 install torch==1.8.1+cpu torchvision==0.9.1+cpu torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html

RUN pip3 install matplotlib
RUN pip3 install scikit-learn
RUN pip3 install pandas
RUN pip3 install notebook
RUN pip3 install h5py
RUN pip3 install tensorboard
RUN pip3 install tensorboardX
RUN pip3 install syft
RUN pip3 install smt
RUN pip3 install tqdm
RUN pip3 install librosa
RUN apt-get update
RUN apt-get install libsndfile1 --yes
